#include <HumidityReaderDummy.h>
#include <HumidityReader.h>
#include <PythonScript.h>
#include <Scheduler.h>
#include <StepperMotorArduinoDummy.h>
#include <StepperMotorArduino.h>
#include <StepperMotorStandaDummy.h>
#include <StepperMotorStanda.h>
#include <Writer.h>
#include "Digitizer.h"
